//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadifyChallengeWebService
{
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.Web;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute]
    public enum TriangleType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equilateral = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Isosceles = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scalene = 3,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute]
    public interface IRedPill
    {

        [System.ServiceModel.OperationContractAttribute]
        [WebInvoke(Method = "GET",
            ResponseFormat = WebMessageFormat.Json,
            BodyStyle = WebMessageBodyStyle.Wrapped,
            UriTemplate = "/api/")]

        //[WebInvoke(Method = "GET",
        //    ResponseFormat = WebMessageFormat.Xml,
        //    BodyStyle = WebMessageBodyStyle.Wrapped,
        //    UriTemplate = "/{id}")]
        System.Guid WhatIsYourToken();

        [System.ServiceModel.OperationContractAttribute]

        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentOutOfRangeException))]

        [WebInvoke(Method = "GET",
            ResponseFormat = WebMessageFormat.Json,
            BodyStyle = WebMessageBodyStyle.Wrapped,
            UriTemplate = "/api/Fibonacci?n={n}")]
        long FibonacciNumber(long n);



        [System.ServiceModel.OperationContractAttribute]

        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentOutOfRangeException))]
        [WebInvoke(Method = "GET",
            ResponseFormat = WebMessageFormat.Json,
            BodyStyle = WebMessageBodyStyle.Wrapped,
            UriTemplate = "/api/TriangleType?a={a}&b={b}&c={c}")]
        TriangleType WhatShapeIsThis(int a, int b, int c);



        [System.ServiceModel.OperationContractAttribute]

        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentOutOfRangeException))]
        [WebInvoke(Method = "GET",
            ResponseFormat = WebMessageFormat.Json,
            BodyStyle = WebMessageBodyStyle.Wrapped,
            UriTemplate = "/api/ReverseWords?sentence={s}")]
        string ReverseWords(string s);


    }
}
